source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LJAELOS1S' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
use_frameworks!
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SnapKit'
    pod 'BluetoothKit'
    pod 'XCGLogger'
    pod 'Kingfisher'
    
  # Pods for LJAELOS1S

  target 'LJAELOS1STests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LJAELOS1SUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
